<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Backend\Mulkora.Contracts\Mulkora.Contracts.csproj" />
      <ProjectReference Include="..\..\Backend\Mulkora.WebApi\Mulkora.WebApi.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Areas\Admin\Data\" />
      <Folder Include="Areas\Admin\Models\" />
      <Folder Include="Areas\Admin\Pages\" />
      <Folder Include="Pages\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\about.html" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\booking.html" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\contact.html" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\css\bootstrap.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\css\style.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\hotel-html-template.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\about-1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\about-2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\about-3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\about-4.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\carousel-1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\carousel-2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\room-1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\room-2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\room-3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\team-1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\team-2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\team-3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\team-4.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\testimonial-1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\testimonial-2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\testimonial-3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\testimonial-4.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\img\video.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\index.html" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\js\main.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\animate\animate.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\animate\animate.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\counterup\counterup.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\easing\easing.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\easing\easing.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\assets\ajax-loader.gif" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\assets\owl.carousel.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\assets\owl.carousel.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\assets\owl.theme.default.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\assets\owl.theme.default.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\assets\owl.theme.green.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\assets\owl.theme.green.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\assets\owl.video.play.png" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\LICENSE" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\owl.carousel.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\owlcarousel\owl.carousel.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\tempusdominus\css\tempusdominus-bootstrap-4.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\tempusdominus\css\tempusdominus-bootstrap-4.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\tempusdominus\js\moment-timezone.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\tempusdominus\js\moment.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\tempusdominus\js\tempusdominus-bootstrap-4.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\tempusdominus\js\tempusdominus-bootstrap-4.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\waypoints\links.php" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\waypoints\waypoints.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\wow\wow.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\lib\wow\wow.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\READ-ME.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\room.html" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\bootstrap-grid.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\bootstrap-reboot.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\bootstrap-utilities.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\bootstrap.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\forms\_floating-labels.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\forms\_form-check.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\forms\_form-control.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\forms\_form-range.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\forms\_form-select.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\forms\_form-text.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\forms\_input-group.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\forms\_labels.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\forms\_validation.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\helpers\_clearfix.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\helpers\_colored-links.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\helpers\_position.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\helpers\_ratio.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\helpers\_stretched-link.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\helpers\_text-truncation.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\helpers\_visually-hidden.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_alert.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_border-radius.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_box-shadow.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_breakpoints.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_buttons.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_caret.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_clearfix.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_color-scheme.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_container.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_deprecate.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_forms.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_gradients.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_grid.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_image.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_list-group.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_lists.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_pagination.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_reset-text.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_resize.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_table-variants.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_text-truncate.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_transition.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_utilities.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\mixins\_visually-hidden.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\utilities\_api.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\vendor\_rfs.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_accordion.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_alert.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_badge.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_breadcrumb.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_button-group.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_buttons.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_card.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_carousel.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_close.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_containers.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_dropdown.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_forms.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_functions.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_grid.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_helpers.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_images.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_list-group.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_mixins.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_modal.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_nav.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_navbar.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_offcanvas.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_pagination.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_popover.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_progress.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_reboot.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_root.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_spinners.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_tables.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_toasts.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_tooltip.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_transitions.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_type.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_utilities.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\scss\bootstrap\scss\_variables.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\service.html" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\team.html" />
      <_ContentIncludedByDefault Remove="wwwroot\hotel-html-template\testimonial.html" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Service\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Service\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Service\Update.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Services\Update.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Staff\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Staff\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Staff\Update.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Testimonial\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Testimonial\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Testimonial\Update.cshtml" />
    </ItemGroup>

</Project>
